resolver: lts-11.7
packages:
- .
- hie-plugin-api

- location:
    ./submodules/HaRe
  extra-dep: true

- location:
    ./submodules/ghc-mod
  extra-dep: true
  subdirs:
    - .
    - core

- location:
    ./submodules/cabal-helper
  extra-dep: true

- location:
    ./submodules/haskell-lsp
  extra-dep: true
  subdirs:
    - .
    - haskell-lsp-types

extra-deps:
- brittany-0.11.0.0
- butcher-1.3.1.1
- constrained-dynamic-0.1.0.0
- czipwith-1.0.1.0
- haddock-api-2.18.1
- haddock-library-1.4.4
- sorted-list-0.2.1.0
- syz-0.2.0.0

flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true

nix:
  packages: [ icu libcxx zlib ]
