resolver: nightly-2019-05-31 # GHC 8.6.5
packages:
- .
- hie-plugin-api

extra-deps:
- ./submodules/HaRe
- ./submodules/cabal-helper
- ./submodules/ghc-mod
- ./submodules/ghc-mod/core
- ./submodules/ghc-mod/ghc-project-types

- ansi-terminal-0.8.2
- ansi-wl-pprint-0.6.8.2
- brittany-0.12.0.0
- butcher-1.3.2.1
- cabal-plan-0.4.0.0
- constrained-dynamic-0.1.0.0
- deque-0.2.7
- floskell-0.10.1
- ghc-exactprint-0.5.8.2
- ghc-lib-parser-8.8.0.20190424
- haddock-api-2.22.0
- haskell-lsp-0.14.0.0
- haskell-lsp-types-0.14.0.1
- hlint-2.1.24
- hsimport-0.10.0
- lsp-test-0.5.4.0
- monad-dijkstra-0.1.1.2@rev:1
- monad-memo-0.4.1
- multistate-0.8.0.1
- syz-0.2.0.0
- temporary-1.2.1.1
# To make build work in windows 7
- unix-time-0.4.7
- yaml-0.8.32

flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true

# allow-newer: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
