resolver: nightly-2020-03-09  # Last GHC 8.8.2
packages:
- .
- hie-plugin-api

extra-deps:
# - ./submodules/HaRe

- apply-refact-0.7.0.0
- brittany-0.12.1.1
- bytestring-trie-0.2.5.0
# - cabal-helper-1.0.0.0
- github: jneira/cabal-helper
  commit: ffb1f57a5ffc6b7ac3c46a9974c4420a6d2bb9b2
- clock-0.7.2
- constrained-dynamic-0.1.0.0
- floskell-0.10.2
- ghc-lib-parser-8.8.2.20200205
- ghc-lib-parser-ex-8.8.5.3
- haddock-api-2.23.1
- haddock-library-1.8.0
- haskell-lsp-0.20.0.0
- haskell-lsp-types-0.20.0.0
- lsp-test-0.10.1.0
- hie-bios-0.4.0
- hlint-2.2.11
- hoogle-5.0.17.15
- hsimport-0.11.0@sha256:e8f1774aff97215d7cc3a6c81635fae75b80af182f732f8fe28d1ed6eb9c7401,3170
- ilist-0.3.1.0
- monad-dijkstra-0.1.1.2
- ormolu-0.0.3.1
- resourcet-1.2.3 # forced by unliftio-core >= 0.2
- semigroups-0.18.5
- temporary-1.2.1.1
- unliftio-0.2.12.1
- unliftio-core-0.2.0.1

flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true

# allow-newer: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
