#resolver: lts-3.11
# Nightly has ghc-mod/cabal-helper, not in lts yet
resolver: nightly-2015-10-27
packages:
- .
- haskell-ide-example-plugin2
- haskell-ide-plugin-api
- haskell-ide-plugin-hare
extra-deps:
 - logging-3.0.2
 - HaRe-0.8.2.0
 - rosezipper-0.2
 - syz-0.2.0.0
# - ghc-mod-5.4.0.0
# - cabal-helper-0.6.1.0
