resolver: nightly-2018-07-26 # GHC 8.4.3
packages:
- .
- hie-plugin-api

- location:
    ./submodules/HaRe
  extra-dep: true

- location:
    ./submodules/ghc-mod
  extra-dep: true
  subdirs:
    - .
    - core

- location:
    ./submodules/haskell-lsp
  extra-dep: true
  subdirs:
    - .
    - haskell-lsp-types

extra-deps:
- aeson-1.3.1.1
- apply-refact-0.5.0.0
- base-compat-0.9.3
- brittany-0.11.0.0
- cabal-helper-0.8.1.0
- cabal-plan-0.3.0.0
- constrained-dynamic-0.1.0.0
- ekg-0.4.0.15
- ekg-json-0.1.0.6
- ghc-exactprint-0.5.6.1
- haddock-api-2.20.0
- hsimport-0.8.6
- lsp-test-0.2.1.0
- syz-0.2.0.0
- temporary-1.2.1.1
- yaml-0.8.32

flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
