resolver: nightly-2018-04-24 # GHC 8.4.2
packages:
- .
- hie-plugin-api

- location:
    ./submodules/HaRe
  extra-dep: true

- location:
    ./submodules/cabal-helper
  extra-dep: true

- location:
    ./submodules/ghc-mod
  extra-dep: true
  subdirs:
    - .
    - core

- location:
    ./submodules/yi-rope
  extra-dep: true


extra-deps:
- apply-refact-0.5.0.0
- brittany-0.11.0.0
- butcher-1.3.1.1
- constrained-dynamic-0.1.0.0
- czipwith-1.0.1.0
- data-tree-print-0.1.0.1
- haddock-api-2.19.0.1
- haskell-lsp-0.2.1.0
- haskell-lsp-types-0.2.1.0
- sorted-list-0.2.1.0
- syz-0.2.0.0


flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true

nix:
  packages: [ icu libcxx zlib ]
