resolver: nightly-2016-01-22
packages:
- .
- hie-apply-refact
- hie-base
- hie-example-plugin2
- hie-eg-plugin-async
- hie-plugin-api
- hie-ghc-mod
- hie-ghc-tree
- hie-hare
- hie-docs-generator
- location:
    git: https://github.com/mpickering/apply-refact.git
    commit: 402458652844c1a0f42b15123e0ceff761919415
  extra-dep: true
extra-deps:
  - ghc-dump-tree-0.2.0.0
  - ghc-7.10.3
