jobs:
- job: Linux_Stack
  timeoutInMinutes: 0
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      stack-def:
        YAML_FILE: stack.yaml
      stack-8.6.5:
        YAML_FILE: stack-8.6.5.yaml
      stack-8.6.4:
        YAML_FILE: stack-8.6.4.yaml
      stack-8.6.3:
        YAML_FILE: stack-8.6.3.yaml
      stack-8.6.2:
        YAML_FILE: stack-8.6.2.yaml
      stack-8.6.1:
        YAML_FILE: stack-8.6.1.yaml
      stack-8.4.4:
        YAML_FILE: stack-8.4.4.yaml
      stack-8.4.3:
        YAML_FILE: stack-8.4.3.yaml
      stack-8.4.2:
        YAML_FILE: stack-8.4.2.yaml
      stack-8.2.2:
        YAML_FILE: stack-8.2.2.yaml
  variables:
    STACK_ROOT: /home/vsts/.stack
  steps:
  - task: CacheBeta@0
    inputs:
      key: stack-root | $(Agent.OS) | $(Build.SourcesDirectory)/$(YAML_FILE)
      path: .azure-cache
      cacheHitVar: CACHE_RESTORED
    displayName: "Download cache"
  - bash: |
      mkdir -p $STACK_ROOT
      tar -xzf .azure-cache/stack-root.tar.gz -C /
      mkdir -p .stack-work
      tar -xzf .azure-cache/stack-work.tar.gz
    displayName: "Unpack cache"
    condition: eq(variables.CACHE_RESTORED, 'true')
  - bash: |
      git submodule sync
      git submodule update --init
    displayName: Sync submodules
  - bash: |
      mkdir -p ~/.local/bin
      curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | \
        tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    displayName: Install stack
  - bash: |
      source .azure/linux.bashrc
      stack setup --stack-yaml $(YAML_FILE)
    displayName: Install GHC
  - bash: |
      source .azure/linux.bashrc
      stack  --stack-yaml $(YAML_FILE) --install-ghc build --only-dependencies
    displayName: Build dependencies
  - bash: |
      source .azure/linux.bashrc
      stack build --stack-yaml $(YAML_FILE)
    displayName: Build `hie`
  - bash: |
      source .azure/linux.bashrc
      stack build --stack-yaml $(YAML_FILE) --test --bench --only-dependencies
      stack install --stack-yaml $(YAML_FILE) # `hie` binary required for tests
    displayName: Build Test-dependencies
  - bash: |
      sudo apt update
      sudo apt install z3
    displayName: "Install Runtime Test-Dependencies: z3"
  - bash: |
      source .azure/linux.bashrc
      stack install --resolver=lts-11.18 liquid-fixpoint-0.7.0.7 dotgen-0.4.2 fgl-visualize-0.1.0.1 located-base-0.1.1.1 liquidhaskell-0.8.2.4
    displayName: "Install Runtime Test-Dependencies: liquidhaskell"
  # - bash: |
  #     source .azure/linux.bashrc
  #     stack test --stack-yaml $(YAML_FILE)
  #   displayName: Run Test
  - bash: |
      mkdir -p .azure-cache
      tar -czf .azure-cache/stack-root.tar.gz $STACK_ROOT
      tar -czf .azure-cache/stack-work.tar.gz .stack-work
    displayName: "Pack cache"
