jobs:
- job: Linux_installhs_Stack
  timeoutInMinutes: 0
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      shake:
        YAML_FILE: install/shake.yaml
  steps:
  - bash: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root
      mkdir -p ~/.local/bin
      curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | \
        tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    displayName: Install stack
  - bash: |
      source .azure/linux.bashrc
      stack setup --stack-yaml $(YAML_FILE)
    displayName: Install GHC
  - bash: |
      source .azure/linux.bashrc
      stack --stack-yaml $(YAML_FILE) --install-ghc build --only-dependencies
    displayName: Build dependencies
  - bash: |
      source .azure/linux.bashrc
      stack build --stack-yaml $(YAML_FILE)
    displayName: Build `hie-install`
  - bash: |
      source .azure/linux.bashrc
      stack install.hs help
    displayName: Run help of `install.hs`
  - bash: |
      source .azure/linux.bashrc
      stack install.hs latest
    displayName: Run latest target of `install.hs`
