jobs:
- job: MacOs_installhs_Stack
  timeoutInMinutes: 0
  pool:
    vmImage: macOS-10.13
  strategy:
    matrix:
      shake:
        YAML_FILE: install/shake.yaml
  steps:
  - bash: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root
      mkdir -p ~/.local/bin
      curl -skL https://get.haskellstack.org/stable/osx-x86_64.tar.gz | \
        tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin;
    displayName: Install stack
  - bash: |
      source .azure/macos.bashrc
      stack setup --stack-yaml $(YAML_FILE)
    displayName: Install GHC
  - bash: |
      source .azure/macos.bashrc
      stack --stack-yaml $(YAML_FILE) --install-ghc build --only-dependencies
    displayName: Build dependencies
  - bash: |
      source .azure/macos.bashrc
      stack build --stack-yaml $(YAML_FILE)
    displayName: Build `hie-install`
  - bash: |
      source .azure/macos.bashrc
      stack install.hs help
    displayName: Run help of `instal.hs`
