jobs:
- job: Windows_Stack
  timeoutInMinutes: 0
  pool:
    vmImage: windows-2019
  strategy:
    matrix:
      stack-def:
        YAML_FILE: stack.yaml
      stack-8.6.5:
        YAML_FILE: stack-8.6.5.yaml
      stack-8.6.4:
        YAML_FILE: stack-8.6.4.yaml
      stack-8.6.2:
        YAML_FILE: stack-8.6.2.yaml
      stack-8.6.1:
        YAML_FILE: stack-8.6.1.yaml
      stack-8.4.4:
        YAML_FILE: stack-8.4.4.yaml
      stack-8.4.3:
        YAML_FILE: stack-8.4.3.yaml
      stack-8.4.2:
        YAML_FILE: stack-8.4.2.yaml
      stack-8.2.2:
        YAML_FILE: stack-8.2.2.yaml
  variables:
    STACK_ROOT: "C:\\sr"

  steps:
  - task: CacheBeta@0
    inputs:
      key: |
        "stack-root"
        $(Agent.OS)
        $(Build.SourcesDirectory)/$(YAML_FILE)
      path: $(STACK_ROOT)
    displayName: "Cache stack-root"
  - task: CacheBeta@0
    inputs:
      key: |
        "stack-work"
        $(Agent.OS)
        $(Build.SourcesDirectory)/$(YAML_FILE)
      path: .stack-work
    displayName: "Cache stack-work"
  - bash: |
      git submodule sync
      git submodule update --init
    displayName: Sync submodules
  - bash: |
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
    displayName: Install stack
  - bash: |
      source .azure/windows.bashrc
      stack setup --stack-yaml $(YAML_FILE)
    displayName: Install GHC
  - bash: |
      source .azure/windows.bashrc
      stack --stack-yaml $(YAML_FILE) --install-ghc build --only-dependencies
    displayName: Build dependencies
  - bash: |
      source .azure/windows.bashrc
      stack build --stack-yaml $(YAML_FILE)
    displayName: Build `hie`
  - bash: |
      source .azure/windows.bashrc
      stack build --stack-yaml $(YAML_FILE) --test --bench --only-dependencies
      stack install --stack-yaml $(YAML_FILE) # `hie` binary required for tests
      stack exec --stack-yaml $(YAML_FILE) hoogle generate
    displayName: Build Test-dependencies
  - bash: |
      # TODO: try to install automatically (`choco install z3` fails and pacman is not installed)
      mkdir -p /usr/local
      curl -L https://github.com/Z3Prover/z3/releases/download/Z3-4.8.5/z3-4.8.5-x64-win.zip -o /usr/local/z3.zip
      unzip -o /usr/local/z3.zip -d /usr/local/
    displayName: "Install Runtime Test-Dependencies: z3"
  - bash: |
      source .azure/windows.bashrc
      stack install --resolver=lts-11.18 liquid-fixpoint-0.7.0.7 dotgen-0.4.2 fgl-visualize-0.1.0.1 located-base-0.1.1.1 liquidhaskell-0.8.2.4
      liquid -v
    displayName: "Install Runtime Test-Dependencies: liquidhaskell"
  # - bash: |
  #     source .azure/windows.bashrc
  #     stack test --stack-yaml $(YAML_FILE) :unit-test
  #   displayName: Run Test
