jobs:
- job: Windows_Stack
  timeoutInMinutes: 0
  pool:
    vmImage: windows-2019
  strategy:
    matrix:
      # default stack.yaml uses ghc-8.8.2 so we can't use it for windows
      # TODO: Enable it when it uses ghc-8.8.3
      # stack-def:
      #  YAML_FILE: stack.yaml
      stack-8.8.3:
        YAML_FILE: stack-8.8.3.yaml
      # ghc versions 8.8.1 and 8.8.2 are not usable in windows 
      # due to https://gitlab.haskell.org/ghc/ghc/issues/17575
      stack-8.6.5:
        YAML_FILE: stack-8.6.5.yaml
      stack-8.6.4:
        YAML_FILE: stack-8.6.4.yaml
      stack-8.4.4:
        YAML_FILE: stack-8.4.4.yaml
      stack-8.4.3:
        YAML_FILE: stack-8.4.3.yaml
      stack-8.4.2:
        YAML_FILE: stack-8.4.2.yaml
  variables:
    STACK_ROOT: "C:\\sr"
    CABAL_VERSION: "3.0.0.0"
    CABAL_STORE_DIR: "C:\\sd"

  steps:
  - task: Cache@2
    inputs:
      key: '"stack-v3" | "$(Agent.OS)" | $(Build.SourcesDirectory)/$(YAML_FILE)'
      path: .azure-cache
      cacheHitVar: CACHE_RESTORED
    displayName: "Cache stack-root"
  - bash: |
      mkdir -p $STACK_ROOT
      tar -vxzf .azure-cache/stack-root.tar.gz -C /c
      mkdir -p .stack-work
      tar -vxzf .azure-cache/stack-work.tar.gz
    displayName: "Unpack cache"
    condition: eq(variables.CACHE_RESTORED, 'true')
  - bash: |
      git submodule sync
      git submodule update --init
    displayName: Sync submodules
  - bash: |
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
      mkdir -p "$STACK_ROOT"
    displayName: Install stack
  - bash: |
      source .azure/windows-stack.bashrc
      stack setup --stack-yaml $(YAML_FILE)
      stack setup --resolver=lts-13.20 # for liquidhaskell
    displayName: Install GHC
  - bash: |
      source .azure/windows-stack.bashrc
      STACK_CMD="stack build --stack-yaml $(YAML_FILE) --only-dependencies"
      # Some executions fails with spurious errors installing executables
      $STACK_CMD || $STACK_CMD
    displayName: Build dependencies
  - bash: |
      source .azure/windows-stack.bashrc
      stack build --stack-yaml $(YAML_FILE)
    displayName: Build `hie`
  - bash: |
      source .azure/windows-stack.bashrc
      stack install --stack-yaml $(YAML_FILE) # `hie` binary required locally for tests
      mkdir .azure-deploy
      stack install --stack-yaml $(YAML_FILE) --local-bin-path .azure-deploy
      cd .azure-deploy
      if [ $YAML_FILE != "stack.yaml" ]; then
        GHC_VERSION=${YAML_FILE:6:5}
        GHC_MAJOR_VERSION=${YAML_FILE:6:3}
        cp hie.exe hie-$GHC_VERSION.exe
        cp hie.exe hie-$GHC_MAJOR_VERSION.exe
      else
        GHC_VERSION=nightly
      fi
      ARTIFACT_NAME=hie-$(hie --numeric-version)-ghc-$GHC_VERSION-windows-x86_64
      7z a "$(Build.ArtifactStagingDirectory)/$ARTIFACT_NAME.zip" *
    displayName: Install `hie`
  - bash: |
      source .azure/windows-stack.bashrc
      stack build --stack-yaml $(YAML_FILE) --test --bench --only-dependencies
    displayName: Build Test-dependencies
  - bash: |
      mkdir -p /usr/local
      curl -L https://github.com/Z3Prover/z3/releases/download/Z3-4.8.5/z3-4.8.5-x64-win.zip -o /usr/local/z3.zip
      unzip -o /usr/local/z3.zip -d /usr/local/
    displayName: "Install Runtime Test-Dependencies: z3"
  - bash: |
      source .azure/windows-stack.bashrc
      # To make stack not pick default stack.yaml if it uses the same ghc than lts-13.20
      cd "$(Agent.TempDirectory)"
      stack install --resolver=lts-13.20 liquid-fixpoint-0.8.0.2 liquidhaskell-0.8.6.2
    displayName: "Install Runtime Test-Dependencies: liquidhaskell"
  - bash: |
      source .azure/windows-stack.bashrc
      stack build hoogle --stack-yaml=$(YAML_FILE)
      stack exec hoogle generate --stack-yaml=$(YAML_FILE)
    displayName: "Install Runtime Test-Dependencies: hoogle database"
  - bash: |
      source .azure/windows-stack.bashrc
      choco install -y cabal --version $CABAL_VERSION
      /C/ProgramData/chocolatey/bin/RefreshEnv.cmd
      cabal v2-update
      echo "store-dir: $CABAL_STORE_DIR" >> $CABAL_ROOT/config
    displayName: "Install Runtime Test-Dependencies: cabal"
  - bash: |
      source .azure/windows-stack.bashrc
      # hie assumes that ghc is in path for cabal cradles (Haskell.Ide.Engine.Cradle.execProjectGhc)
      export PATH="$(stack path --compiler-bin --stack-yaml $YAML_FILE)":$PATH
      stack test :unit-test --stack-yaml $(YAML_FILE)
    displayName: "Run Test: unit-test"
  - bash: |
      source .azure/windows-stack.bashrc
      # Needed for wrapper-test
      stack setup --stack-yaml stack-8.8.1.yaml
      stack setup --stack-yaml stack-8.6.5.yaml
      # TODO: Enable :dispatcher-test suite
      stack test :plugin-dispatcher-test :wrapper-test --stack-yaml $(YAML_FILE)
    displayName: "Run Test: dispatcher-test, plugin-dispatcher-test and wrapper-test"
  - bash: |
      source .azure/windows-stack.bashrc
      # TODO: Enable hover test for ghc-8.6.4
      if [ $YAML_FILE != "stack-8.6.4.yaml" ]; then
          stack test --stack-yaml $(YAML_FILE) :func-test
      else
          stack test --stack-yaml $(YAML_FILE) :func-test --ta="--skip \"/Hover/hover/works\""
      fi
    displayName: "Run Test: func-test"
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: hie-$(Agent.OS)-$(YAML_FILE)
    condition: in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues')
  - bash: |
      mkdir -p .azure-cache
      tar -vczf .azure-cache/stack-root.tar.gz $(cygpath $STACK_ROOT)
      tar -vczf .azure-cache/stack-work.tar.gz .stack-work
    displayName: "Pack cache"
