jobs:
- job: Windows_Stack
  timeoutInMinutes: 0
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      stack-def:
        YAML_FILE: stack.yaml
      stack-8.6.5:
        YAML_FILE: stack-8.6.5.yaml
      stack-8.6.4:
        YAML_FILE: stack-8.6.4.yaml
      stack-8.6.2:
        YAML_FILE: stack-8.6.2.yaml
      stack-8.6.1:
        YAML_FILE: stack-8.6.1.yaml
      stack-8.4.4:
        YAML_FILE: stack-8.4.4.yaml
      stack-8.4.3:
        YAML_FILE: stack-8.4.3.yaml
      stack-8.4.2:
        YAML_FILE: stack-8.4.2.yaml
      stack-8.2.2:
        YAML_FILE: stack-8.2.2.yaml
  steps:
  - bash: |
      git submodule sync
      git submodule update --init
    displayName: Sync submodules
  - bash: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root
      curl -sSkL http://www.stackage.org/stack/windows-i386 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
    displayName: Install stack
  - bash: |
      source .azure/windows.bashrc
      stack setup --stack-yaml $(YAML_FILE)
    displayName: Install GHC
  - bash: |
      source .azure/linux.bashrc
      stack --stack-yaml $(YAML_FILE) --install-ghc build --only-dependencies
    displayName: Build dependencies
  - bash: |
      source .azure/windows.bashrc
      stack build --stack-yaml $(YAML_FILE)
    displayName: Build `hie`
  - bash: |
      source .azure/windows.bashrc
      stack build --stack-yaml $(YAML_FILE) --test --bench --only-dependencies
      stack install --stack-yaml $(YAML_FILE) # `hie` binary required for tests
      # TODO: get `cabal` binary from somewhere else?
      stack setup --stack-yaml=stack-8.6.5.yaml
      stack install --stack-yaml=stack-8.6.5.yaml cabal-install-2.4.1.0
      stack exec --stack-yaml $(YAML_FILE) hoogle generate
      choco install z3
      cabal v1-update
      curl -L https://github.com/Z3Prover/z3/releases/download/Z3-4.8.5/z3-4.8.5-x64-win.zip -o /usr/local/z3.zip
      unzip -o /usr/local/z3.zip -d /usr/local/
      stack setup --stack-yaml=stack-8.2.2.yaml
      cabal v1-install liquidhaskell-0.8.2.4 --symlink-bindir=$HOME/.local/bin -w $(stack path --stack-yaml=stack-8.2.2.yaml --compiler-exe)
    displayName: Build Test-dependencies
  - bash: |
      source .azure/windows.bashrc
      stack test --stack-yaml $(YAML_FILE) :unit-test
    displayName: Run Test
